### ISSUE TITLE
Can't load SR model's weights - Missing keys in state_dict when trying to run test.py

### ISSUE THREAD

**Issue by egedib** [widefield2sim/w2s#2]
I can't run the super resolution test file. I'm using the newest (1.4.0) PyTorch, also my Cuda is 10.1. 
The net I want to use is RRDBNet (**--net ours**).

`RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.RRDB_trunk.12.RDB1.conv1.weight", "module.RRDB_trunk.12.RDB1.conv1.bias", "module.RRDB_trunk.12.RDB1.conv2.weight", "module.RRDB_trunk.12.RDB1.conv2.bias", "module.RRDB_trunk.12.RDB1.conv3.weight", "module.RRDB_trunk.12.RDB1.conv3.bias", "module.RRDB_trunk.12.RDB1.conv4.weight", "module.RRDB_trunk.12.RDB1.conv4.bias", "module.RRDB_trunk.12.RDB1.conv5.weight", "module.RRDB_trunk.12.RDB1.conv5.bias", "module.RRDB_trunk.12.RDB2.conv1.weight", "module.RRDB_trunk.12.RDB2.conv1.bias", "module.RRDB_trunk.12.RDB2.conv2.weight", "module.RRDB_trunk.12.RDB2.conv2.bias", "module.RRDB_trunk.12.RDB2.conv3.weight", "module.RRDB_trunk.12.RDB2.conv3.bias", "module.RRDB_trunk.12.RDB2.conv4.weight", "module.RRDB_trunk.12.RDB2.conv4.bias", "module.RRDB_trunk.12.RDB2.conv5.weight", "module.RRDB_trunk.12.RDB2.conv5.bias", "module.RRDB_trunk.12.RDB3.conv1.weight", "module.RRDB_trunk.12.RDB3.conv1.bias", "module.RRDB_trunk.12.RDB3.conv2.weight", "module.RRDB_trunk.12.RDB3.conv2.bias", "module.RRDB_trunk.12.RDB3.conv3.weight", "module.RRDB_trunk.12.RDB3.conv3.bias", "module.RRDB_trunk.12.RDB3.conv4.weight", "module.RRDB_trunk.12.RDB3.conv4.bias", "module.RRDB_trunk.12.RDB3.conv5.weight", "module.RRDB_trunk.12.RDB3.conv5.bias", "module.RRDB_trunk.13.RDB1.conv1.weight", "module.RRDB_trunk.13.RDB1.conv1.bias", "module.RRDB_trunk.13.RDB1.conv2.weight", "module.RRDB_trunk.13.RDB1.conv2.bias", "module.RRDB_trunk.13.RDB1.conv3.weight", "module.RRDB_trunk.13.RDB1.conv3.bias", "module.RRDB_trunk.13.RDB1.conv4.weight", "module.RRDB_trunk.13.RDB1.conv4.bias", "module.RRDB_trunk.13.RDB1.conv5.weight", "module.RRDB_trunk.13.RDB1.conv5.bias", "module.RRDB_trunk.13.RDB2.conv1.weight", "module.RRDB_trunk.13.RDB2.conv1.bias", "module.RRDB_trunk.13.RDB2.conv2.weight", "module.RRDB_trunk.13.RDB2.conv2.bias", "module.RRDB_trunk.13.RDB2.conv3.weight", "module.RRDB_trunk.13.RDB2.conv3.bias", "module.RRDB_trunk.13.RDB2.conv4.weight", "module.RRDB_trunk.13.RDB2.conv4.bias", "module.RRDB_trunk.13.RDB2.conv5.weight", "module.RRDB_trunk.13.RDB2.conv5.bias", "module.RRDB_trunk.13.RDB3.conv1.weight", "module.RRDB_trunk.13.RDB3.conv1.bias", "module.RRDB_trunk.13.RDB3.conv2.weight", "module.RRDB_trunk.13.RDB3.conv2.bias", "module.RRDB_trunk.13.RDB3.conv3.weight", "module.RRDB_trunk.13.RDB3.conv3.bias", "module.RRDB_trunk.13.RDB3.conv4.weight", "module.RRDB_trunk.13.RDB3.conv4.bias", "module.RRDB_trunk.13.RDB3.conv5.weight", "module.RRDB_trunk.13.RDB3.conv5.bias", "module.RRDB_trunk.14.RDB1.conv1.weight", "module.RRDB_trunk.14.RDB1.conv1.bias", "module.RRDB_trunk.14.RDB1.conv2.weight", "module.RRDB_trunk.14.RDB1.conv2.bias", "module.RRDB_trunk.14.RDB1.conv3.weight", "module.RRDB_trunk.14.RDB1.conv3.bias", "module.RRDB_trunk.14.RDB1.conv4.weight", "module.RRDB_trunk.14.RDB1.conv4.bias", "module.RRDB_trunk.14.RDB1.conv5.weight", "module.RRDB_trunk.14.RDB1.conv5.bias", "module.RRDB_trunk.14.RDB2.conv1.weight", "module.RRDB_trunk.14.RDB2.conv1.bias", "module.RRDB_trunk.14.RDB2.conv2.weight", "module.RRDB_trunk.14.RDB2.conv2.bias", "module.RRDB_trunk.14.RDB2.conv3.weight", "module.RRDB_trunk.14.RDB2.conv3.bias", "module.RRDB_trunk.14.RDB2.conv4.weight", "module.RRDB_trunk.14.RDB2.conv4.bias", "module.RRDB_trunk.14.RDB2.conv5.weight", "module.RRDB_trunk.14.RDB2.conv5.bias", "module.RRDB_trunk.14.RDB3.conv1.weight", "module.RRDB_trunk.14.RDB3.conv1.bias", "module.RRDB_trunk.14.RDB3.conv2.weight", "module.RRDB_trunk.14.RDB3.conv2.bias", "module.RRDB_trunk.14.RDB3.conv3.weight", "module.RRDB_trunk.14.RDB3.conv3.bias", "module.RRDB_trunk.14.RDB3.conv4.weight", "module.RRDB_trunk.14.RDB3.conv4.bias", "module.RRDB_trunk.14.RDB3.conv5.weight", "module.RRDB_trunk.14.RDB3.conv5.bias", "module.RRDB_trunk.15.RDB1.conv1.weight", "module.RRDB_trunk.15.RDB1.conv1.bias", "module.RRDB_trunk.15.RDB1.conv2.weight", "module.RRDB_trunk.15.RDB1.conv2.bias", "module.RRDB_trunk.15.RDB1.conv3.weight", "module.RRDB_trunk.15.RDB1.conv3.bias", "module.RRDB_trunk.15.RDB1.conv4.weight", "module.RRDB_trunk.15.RDB1.conv4.bias", "module.RRDB_trunk.15.RDB1.conv5.weight", "module.RRDB_trunk.15.RDB1.conv5.bias", "module.RRDB_trunk.15.RDB2.conv1.weight", "module.RRDB_trunk.15.RDB2.conv1.bias", "module.RRDB_trunk.15.RDB2.conv2.weight", "module.RRDB_trunk.15.RDB2.conv2.bias", "module.RRDB_trunk.15.RDB2.conv3.weight", "module.RRDB_trunk.15.RDB2.conv3.bias", "module.RRDB_trunk.15.RDB2.conv4.weight", "module.RRDB_trunk.15.RDB2.conv4.bias", "module.RRDB_trunk.15.RDB2.conv5.weight", "module.RRDB_trunk.15.RDB2.conv5.bias", "module.RRDB_trunk.15.RDB3.conv1.weight", "module.RRDB_trunk.15.RDB3.conv1.bias", "module.RRDB_trunk.15.RDB3.conv2.weight", "module.RRDB_trunk.15.RDB3.conv2.bias", "module.RRDB_trunk.15.RDB3.conv3.weight", "module.RRDB_trunk.15.RDB3.conv3.bias", "module.RRDB_trunk.15.RDB3.conv4.weight", "module.RRDB_trunk.15.RDB3.conv4.bias", "module.RRDB_trunk.15.RDB3.conv5.weight", "module.RRDB_trunk.15.RDB3.conv5.bias".`

**Comment by widefield2sim** [comment]
Hi,
Can you pull and check again?

**Comment by widefield2sim** [comment]
Hi, I've closed the issue as I think it's solved. please feel free to reopen the issue if it is still there.
