### ISSUE TITLE
undefined function “CovPoolLayer”

### ISSUE THREAD

**Issue by XuZikang** [widefield2sim/w2s#3]
Hi, I read your code train.py, but I find that there is no definition of function *CovPoolLayer* in line 91. When I refer to it in other files, I find many functions called *CovPoolLayer*. Could your please tell me which one is used in train.py? Thank you very much!

```python
        if (opt.net == 'ours'):
            color_gt = torch.cat((x_data,x_data,x_data),1).cuda()
            color_output = torch.cat((output,output,output),1).cuda()
            
            vgg_gt = vgg(color_gt)
            vgg_output = vgg(color_output)
            for i in range(5):
                loss = loss + 0.2*feature_factor*MSEcriterion(vgg_gt[i], vgg_output[i])
                if (i==4):
                    loss += 0.2*feature_factor*MSEcriterion(CovpoolLayer(vgg_gt[i]),CovpoolLayer(vgg_output[i]))
```

**Comment by widefield2sim** [comment]
Hi!
There's one missing import, just add the following line should work:
from model.MPNCOV.MPNCOV import CovPoolLayer

I've updated the codes

**Comment by XuZikang** [comment]
Thank you! It works fine now.

**Comment by widefield2sim** [comment]
Cool!
