### ISSUE TITLE
Denoising ground truth for test set

### ISSUE THREAD

**Issue by alex-krull** [widefield2sim/w2s#6]
Hi, 
Thanks a lot for the great dataset.
Maybe I am overlooking something, but I cannot find the denoising ground truth data (avg400) for the test set.
Could you please point to where I can find it, or is it indeed missing by accident?
Thanks for your help!

**Comment by widefield2sim** [comment]
Hi, 
Thank you for your interest and your positive comment!
We have uploaded the ground-truth data (avg40o noise-free Widefield) to the test directory (please check this commit:  https://github.com/widefield2sim/w2s/commit/c674e02557b646598a6d0d521ea5bd1e24de971a).

**Comment by alex-krull** [comment]
Great! Thanks!
